# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b3214d808375922141b442f6fb34e137ae4f359de82a1060a15804756bd3d287cd67e6a2fa53a335b2ef60411b54c65b965ce43f60ef1639cce6c915ed995eba

test:
  secret_key_base: 1e5803916848905a4356ac11219ef60256e7d1f2b8689f04506aa3bd140b33d9784d8e0a64e0d39cf3d0500d3ea4b3390756d266d0d528ace1ee7a76fee22a31

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
